apiVersion: v1
kind: Service
metadata:
  name: influxdb
  labels:
    app: influxdb
spec:
  ports:
    - port: 8086
  selector:
    app: influxdb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb
  labels:
    app: influxdb
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: influxdb
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      containers:
      - name: influxdb
        image: influxdb
        imagePullPolicy: Never
        ports:
        - containerPort: 8086
        livenessProbe:
          exec:
            command:
            - pgrep
            - influxd
          initialDelaySeconds: 25
          periodSeconds: 5
        volumeMounts:
        - name: start-sh
          mountPath: /scripts
        - name: influxdb-config
          mountPath: /etc/influxdb.conf
          subPath: influxdb.conf
        - name: telegraf-config
          mountPath: /etc/telegraf.conf
          subPath: telegraf.conf
        - name: influxdb-pv
          mountPath: /var/lib/influxdb
      volumes:
      - name: start-sh
        configMap:
          name: influxdb-config
          items:
          - key: start.sh
            path: start.sh
          defaultMode: 0751
      - name: influxdb-config
        configMap:
          name: influxdb-config
          items:
          - key: influxdb.conf
            path: influxdb.conf
      - name: telegraf-config
        configMap:
          name: influxdb-config
          items:
          - key: telegraf.conf
            path: telegraf.conf
      - name: influxdb-pv
        persistentVolumeClaim:
          claimName: influxdb-pvc
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: influxdb-config
data:
  start.sh: |
    #! /bin/sh

    influxd -config /etc/influxdb.conf & sleep 5

    echo "CREATE USER telegraf WITH PASSWORD 'secure'" | influx
    echo "CREATE DATABASE ftps" | influx
    echo "CREATE DATABASE grafana" | influx
    echo "CREATE DATABASE influxdb" | influx
    echo "CREATE DATABASE mysql" | influx
    echo "CREATE DATABASE nginx" | influx
    echo "CREATE DATABASE phpmyadmin" | influx
    echo "CREATE DATABASE wordpress" | influx

    telegraf --config /etc/telegraf.conf
  influxdb.conf: |
    [meta]
      dir = "/var/lib/influxdb/meta"
    [data]
      dir = "/var/lib/influxdb/data"
      wal-dir = "/var/lib/influxdb/wal"
    [http]
      enabled = true
  telegraf.conf: |
    [agent]
      hostname = "ft_services"
      interval = "10s"
      flush_interval = "10s"
      round_interval = true
    [[outputs.influxdb]]
      urls = ["http://127.0.0.1:8086"]
      database = "influxdb"
      timeout = "5s"
      username = "telegraf"
      password = "secure"
    [[inputs.cpu]]
      percpu = true
      totalcpu = true
      collect_cpu_time = false
      report_active = false
    [[inputs.disk]]
      ignore_fs = ["tmpfs", "devtmpfs", "devfs"]
    [[inputs.diskio]]
    [[inputs.kernel]]
    [[inputs.mem]]
    [[inputs.processes]]
    [[inputs.swap]]
    [[inputs.system]]
    [[inputs.netstat]]
    [[inputs.net]]
