apiVersion: v1
kind: Service
metadata:
  name: ftps
  annotations:
    metallb.universe.tf/address-pool: default
    metallb.universe.tf/allow-shared-ip: kee
  labels:
    app: ftps
spec:
  type: LoadBalancer
  ports:
    - name: ftps
      port: 21
    - name: pasv
      port: 30001
  selector:
    app: ftps
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps
        imagePullPolicy: Never
        ports:
        - name: ftps
          containerPort: 21
        - name: pasv
          containerPort: 30001
        livenessProbe:
          exec:
            command:
            - pgrep
            - telegraf
          initialDelaySeconds: 25
          periodSeconds: 5
        volumeMounts:
        - name: start-sh
          mountPath: /scripts
        - name: vsftpd-config
          mountPath: /etc/vsftpd.conf
          subPath: vsftpd.conf
        - name: telegraf-config
          mountPath: /etc/telegraf.conf
          subPath: telegraf.conf
      volumes:
      - name: start-sh
        configMap:
          name: vsftpd-config
          items:
          - key: start.sh
            path: start.sh
          defaultMode: 0751
      - name: vsftpd-config
        configMap:
          name: vsftpd-config
          items:
          - key: vsftpd.conf
            path: vsftpd.conf
      - name: telegraf-config
        configMap:
          name: vsftpd-config
          items:
          - key: telegraf.conf
            path: telegraf.conf
---
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: vsftpd-config
  data:
    start.sh: |
      #! /bin/sh

      echo "root:secure" | chpasswd

      if [ ! -f /etc/ssl/certs/selfsigned.crt ]; then
          openssl req -newkey rsa:2048 -x509 -sha256 -days 365 -nodes \
          -subj "/C=BE/ST=Brussels/L=Brussels/O=19OU=floogman/CN=ftps" \
          -out /etc/ssl/certs/selfsigned.crt -keyout /etc/ssl/private/selfsigned.key
      elif [ ! -f /etc/ssl/private/selfsigned.key ]; then
          openssl req -newkey rsa:2048 -x509 -sha256 -days 365 -nodes \
          -subj "/C=BE/ST=Brussels/L=Brussels/O=19OU=floogman/CN=ftps" \
          -out /etc/ssl/certs/selfsigned.crt -keyout /etc/ssl/private/selfsigned.key
      fi

      telegraf --config /etc/telegraf.conf &
      vsftpd /etc/vsftpd.conf
    vsftpd.conf: |
      seccomp_sandbox=NO

      # disable anonymous login
      anonymous_enable=NO

      # enable upload by local user
      local_enable=YES
      write_enable=YES

      # configure second port
      pasv_address=192.168.64.102
      pasv_min_port=30001
      pasv_max_port=30001

      # configure SSL
      ssl_enable=YES
      rsa_cert_file=/etc/ssl/certs/selfsigned.crt
      rsa_private_key_file=/etc/ssl/private/selfsigned.key
    telegraf.conf: |
      [agent]
        hostname = "ft_services"
        interval = "10s"
        flush_interval = "10s"
        round_interval = true
      [[outputs.influxdb]]
        urls = ["http://influxdb:8086"]
        database = "ftps"
        timeout = "5s"
        username = "telegraf"
        password = "secure"
      [[inputs.cpu]]
        percpu = true
        totalcpu = true
        collect_cpu_time = false
        report_active = false
      [[inputs.disk]]
        ignore_fs = ["tmpfs", "devtmpfs", "devfs"]
      [[inputs.diskio]]
      [[inputs.kernel]]
      [[inputs.mem]]
      [[inputs.processes]]
      [[inputs.swap]]
      [[inputs.system]]
      [[inputs.netstat]]
      [[inputs.net]]
