apiVersion: v1
kind: Service
metadata:
  name: wordpress
  annotations:
    metallb.universe.tf/address-pool: default
    metallb.universe.tf/allow-shared-ip: kee
  labels:
    app: wordpress
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 5050
  selector:
    app: wordpress
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress
        imagePullPolicy: Never
        ports:
        - containerPort: 5050
        livenessProbe:
          exec:
            command:
            - ./scripts/liveness.sh
          initialDelaySeconds: 25
          periodSeconds: 5
        volumeMounts:
        - name: start-sh
          mountPath: /scripts/start.sh
          subPath: start.sh
        - name: liveness-sh
          mountPath: /scripts/liveness.sh
          subPath: liveness.sh
        - name: wordpress-config
          mountPath: /www/wordpress/wp-config.php
          subPath: wp-config.php
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
        - name: telegraf-config
          mountPath: /etc/telegraf.conf
          subPath: telegraf.conf
      volumes:
      - name: start-sh
        configMap:
          name: wordpress-config
          items:
          - key: start.sh
            path: start.sh
          defaultMode: 0751
      - name: liveness-sh
        configMap:
          name: liveness-sh
          defaultMode: 0751
      - name: wordpress-config
        configMap:
          name: wordpress-config
          items:
          - key: wp-config.php
            path: wp-config.php
      - name: nginx-config
        configMap:
          name: wordpress-config
          items:
          - key: default.conf
            path: default.conf
      - name: telegraf-config
        configMap:
          name: wordpress-config
          items:
          - key: telegraf.conf
            path: telegraf.conf
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-config
data:
  start.sh: |
    #! /bin/sh

    if [ ! -d /run/nginx ]; then
        mkdir -p /run/nginx
    fi

    if [ ! -f /etc/ssl/certs/nginx.crt ]; then
        openssl req -newkey rsa:2048 -x509 -sha256 -days 365 -nodes \
        -subj "/C=BE/ST=Brussels/L=Brussels/O=19OU=floogman/CN=wp" \
        -out /etc/ssl/certs/nginx.crt -keyout /etc/ssl/private/nginx.key
    elif [ ! -f /etc/ssl/private/nginx.key ]; then
        openssl req -newkey rsa:2048 -x509 -sha256 -days 365 -nodes \
        -subj "/C=BE/ST=Brussels/L=Brussels/O=19OU=floogman/CN=wp" \
        -out /etc/ssl/certs/nginx.crt -keyout /etc/ssl/private/nginx.key
    fi

    telegraf --config /etc/telegraf.conf &
    php-fpm7 &
    nginx -g "daemon off;"
  wp-config.php: |
    <?php
    define( 'DB_NAME', 'wordpress' );
    define( 'DB_USER', 'user' );
    define( 'DB_PASSWORD', 'secure' );
    define( 'DB_HOST', 'mysql' );
    define( 'DB_CHARSET', 'utf8' );
    define( 'DB_COLLATE', '' );

    define( 'AUTH_KEY',         'put your unique phrase here' );
    define( 'SECURE_AUTH_KEY',  'put your unique phrase here' );
    define( 'LOGGED_IN_KEY',    'put your unique phrase here' );
    define( 'NONCE_KEY',        'put your unique phrase here' );
    define( 'AUTH_SALT',        'put your unique phrase here' );
    define( 'SECURE_AUTH_SALT', 'put your unique phrase here' );
    define( 'LOGGED_IN_SALT',   'put your unique phrase here' );
    define(	'NONCE_SALT',       'put your unique phrase here' );

    define(	'MYSQL_CLIENT_FLAGS', MYSQLI_CLIENT_SSL);

    $table_prefix = 'wp_';

    define( 'WP_DEBUG', false );
    define( 'WP_DEBUG_LOG', '/tmp/wp-errors.log' );

    if ( ! defined( 'ABSPATH' ) ) {
      define( 'ABSPATH', __DIR__ . '/' );
    }

    require_once ABSPATH . 'wp-settings.php';
  default.conf: |
    server {
        listen                  5050 ssl;
        
        ssl_certificate         /etc/ssl/certs/nginx.crt;
        ssl_certificate_key     /etc/ssl/private/nginx.key;

        root                    /www/wordpress;
        index                   index.php index.html index.htm;

        error_page 497          https://$host:5050$request_uri;

        location ~ \.php$ {
            fastcgi_pass        127.0.0.1:9000;
            include             fastcgi_params;
            include             fastcgi.conf;
        }
    }
  telegraf.conf: |
    [agent]
      hostname = "ft_services"
      interval = "10s"
      flush_interval = "10s"
      round_interval = true

    [[outputs.influxdb]]
      urls = ["http://influxdb:8086"]
      database = "wordpress"

      timeout = "5s"
      username = "telegraf"
      password = "secure"
      
    [[inputs.cpu]]
      percpu = true
      totalcpu = true
      collect_cpu_time = false
      report_active = false
    [[inputs.disk]]
      ignore_fs = ["tmpfs", "devtmpfs", "devfs"]
    [[inputs.diskio]]
    [[inputs.kernel]]
    [[inputs.mem]]
    [[inputs.processes]]
    [[inputs.swap]]
    [[inputs.system]]
    [[inputs.netstat]]
    [[inputs.net]]
